[build]
target = "targets/x86_64-unknown-none.json"
rustflags = "-C link-arg=-Ttargets/kernel.ld"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
